{"name": "Проверка входа пользователя c неправильным username", "status": "passed", "steps": [{"name": "Проверка status_code ответа", "status": "passed", "start": 1714322392173, "stop": 1714322392173}], "start": 1714322391448, "stop": 1714322392174, "uuid": "80460478-ddbe-45b5-bc26-29ee130bd17c", "historyId": "6c86e5ac3e00e9605ac00095df73a6e0", "testCaseId": "6c86e5ac3e00e9605ac00095df73a6e0", "fullName": "tests.test_user_api.TestUserApi#test_user_login_with_incorrect_username", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_api"}, {"name": "subSuite", "value": "TestUserApi"}, {"name": "host", "value": "d45763e349a4"}, {"name": "thread", "value": "96259-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_api"}]}