{"name": "Проверка получения заказа по несуществующему id", "status": "failed", "statusDetails": {"message": "AssertionError: Текст ответа отличается от ожидаемого\nassert 'Order not found' == 'not found'\n  - not found\n  + Order not found\n  ? ++++++", "trace": "self = <test_store_api.TestPetApi object at 0x101ea76d0>\n\n    @allure.title('Проверка получения заказа по несуществующему id')\n    def test_get_store_inventory(self):\n        store_api = StoreApi()\n        response = store_api.get_store_order_by_id(57668486, expected_error=True)\n        check.status_code(404, response)\n>       assert response.json()['message'] == 'not found', \\\n            'Текст ответа отличается от ожидаемого'\nE       AssertionError: Текст ответа отличается от ожидаемого\nE       assert 'Order not found' == 'not found'\nE         - not found\nE         + Order not found\nE         ? ++++++\n\nresponse   = <Response [404]>\nself       = <test_store_api.TestPetApi object at 0x101ea76d0>\nstore_api  = <api_testing.store_api.StoreApi object at 0x101ea7be0>\n\n/Users/annapogrebnik/PycharmProjects/pythonProject1/otus_test_project/tests/test_store_api.py:37: AssertionError"}, "steps": [{"name": "Проверка status_code ответа", "status": "passed", "start": 1714319180494, "stop": 1714319180494}], "start": 1714319179959, "stop": 1714319180495, "uuid": "f40b7a98-b3f8-47de-be52-99d94c0f53d4", "historyId": "fd395fb132282755c495bd57f8fec1ef", "testCaseId": "fd395fb132282755c495bd57f8fec1ef", "fullName": "tests.test_store_api.TestPetApi#test_get_store_inventory", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_store_api"}, {"name": "subSuite", "value": "TestPetApi"}, {"name": "host", "value": "d45763e349a4"}, {"name": "thread", "value": "94545-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_store_api"}]}